main: hieucutevl.donutrtp.DonutRTP
name: DonutRTP
version: 1.0
author: hieucutevl
api-version: "1.21"

description: Random teleport to a specified world
commands:
  rtp:
    description: Random Teleport to a specified world
    usage: /rtp <world>
  customrtp:
    description: Custom Random Teleport
  reload:
    description: Reload DonutRTP config
    usage: /donutrtp:reload
permissions:
  donutrtp.rtp:
    description: "Use /rtp <world> command"
    default: true
  donutrtp.world.*:
    description: "Allow RTP into all worlds"
    default: op
  donutrtp.world.<world>:
    description: "Allow RTP into a specific world (replace <world> with the world name)"
    default: false
  donutrtp.reload:
    description: "Reload the config"
    default: op
  donutrtp.custom:
    description: "Use custom random teleport command"
    default: op
  donutrtp.admin:
    description: "Grants all DonutRTP permissions"
    default: op
    children:
      donutrtp.rtp: true
      donutrtp.world.*: true
      donutrtp.reload: true
      donutrtp.custom: true
